// This file was generated by rustylr 1.33.0
// This generated code is targeting rusty_lr version 4.2.0.
// There might be a build error if the version is not matched.
//
// ================================User Codes Begin================================
#![allow(non_camel_case_types)]
use crate::token::Token;
fn materialize_parenthesized_argument_list(mut arguments: Vec<Vec<Token>>) -> Vec<Token> {
    let mut tokens = Vec::new();
    tokens.push(Token::LeftParen);
    for (argument_index, argument) in arguments.iter_mut().enumerate() {
        if argument_index > 0 {
            tokens.push(Token::Comma);
        }
        tokens.append(argument);
    }
    tokens.push(Token::RightParen);
    tokens
}

// =================================User Codes End=================================
/*
====================================Grammar=====================================

# of terminal classes: 4
# of states: 31

0: MacroInvocationTail -> lparen rparen LexicalToken*
1: MacroInvocationTail -> lparen NonEmptyMacroArgumentList rparen LexicalToken*
2: NonEmptyMacroArgumentList -> MacroArgumentLexeme+ (comma, MacroArgument)*
3: NonEmptyMacroArgumentList -> comma MacroArgumentListAfterLeadingComma
4: MacroArgumentListAfterLeadingComma -> MacroArgumentLexeme* (comma, MacroArgument)*
5: MacroArgumentLexeme -> lparen rparen
6: MacroArgumentLexeme -> lparen NonEmptyMacroArgumentList rparen
7: MacroArgumentLexeme -> [other, ident, ..., <Others>]
8: (comma, MacroArgument) -> comma MacroArgumentLexeme*
9: (comma, MacroArgument)+ -> (comma, MacroArgument)
10: (comma, MacroArgument)+ -> (comma, MacroArgument)+ (comma, MacroArgument)
11: (comma, MacroArgument)* -> (comma, MacroArgument)+
12: (comma, MacroArgument)* ->
13: MacroArgumentLexeme+ -> MacroArgumentLexeme
14: MacroArgumentLexeme+ -> MacroArgumentLexeme+ MacroArgumentLexeme
15: MacroArgumentLexeme* -> MacroArgumentLexeme+
16: MacroArgumentLexeme* ->
17: LexicalToken+ -> [^]
18: LexicalToken+ -> LexicalToken+ [^]
19: LexicalToken* -> LexicalToken+
20: LexicalToken* ->
21: [^] -> [other, ident, ..., <Others>]
22: [^] -> comma
23: [^] -> lparen
24: [^] -> rparen
25: Augmented -> MacroInvocationTail eof

*/
// =============================Generated Codes Begin==============================
/// type alias for `Context`
#[allow(non_camel_case_types, dead_code)]
pub type MacroInvocationTailContext = ::rusty_lr::parser::deterministic::Context<
    MacroInvocationTailParser,
    MacroInvocationTailDataStack,
    u8,
>;
/// type alias for CFG production rule
#[allow(non_camel_case_types, dead_code)]
pub type MacroInvocationTailRule = ::rusty_lr::production::Production<
    MacroInvocationTailTerminalClasses,
    MacroInvocationTailNonTerminals,
>;
/// type alias for runtime parser tables
#[allow(non_camel_case_types, dead_code)]
pub type MacroInvocationTailTables = ::rusty_lr::parser::table::DenseFlatTables<
    MacroInvocationTailTerminalClasses,
    MacroInvocationTailNonTerminals,
    u8,
    u8,
>;
/// type alias for `ParseError`
#[allow(non_camel_case_types, dead_code)]
pub type MacroInvocationTailParseError = ::rusty_lr::parser::deterministic::ParseError<
    Token,
    ::rusty_lr::DefaultLocation,
    ::rusty_lr::DefaultReduceActionError,
>;
/// A enum that represents terminal classes
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord,
)]
#[repr(usize)]
pub enum MacroInvocationTailTerminalClasses {
    TermClass0,
    comma,
    lparen,
    rparen,
    error,
    eof,
}
impl MacroInvocationTailTerminalClasses {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 6usize,
            "Terminal class index {} is out of bounds (max {})",
            value,
            6usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl ::rusty_lr::parser::terminalclass::TerminalClass for MacroInvocationTailTerminalClasses {
    type Term = Token;
    const ERROR: Self = Self::error;
    const EOF: Self = Self::eof;
    fn as_str(&self) -> &'static str {
        match self {
            MacroInvocationTailTerminalClasses::TermClass0 => "[other, ident, ..., <Others>]",
            MacroInvocationTailTerminalClasses::comma => "comma",
            MacroInvocationTailTerminalClasses::lparen => "lparen",
            MacroInvocationTailTerminalClasses::rparen => "rparen",
            MacroInvocationTailTerminalClasses::error => "error",
            MacroInvocationTailTerminalClasses::eof => "eof",
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
    fn from_term(terminal: &Self::Term) -> Self {
        #[allow(unreachable_patterns, unused_variables)]
        match terminal {
            Token::Comma => MacroInvocationTailTerminalClasses::comma,
            Token::LeftParen => MacroInvocationTailTerminalClasses::lparen,
            Token::RightParen => MacroInvocationTailTerminalClasses::rparen,
            _ => MacroInvocationTailTerminalClasses::TermClass0,
        }
    }
}
impl std::fmt::Display for MacroInvocationTailTerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for MacroInvocationTailTerminalClasses {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::terminalclass::TerminalClass;
        write!(f, "{}", self.as_str())
    }
}
/// An enum that represents non-terminal symbols
#[allow(non_camel_case_types, dead_code)]
#[derive(
    Clone,
    Copy,
    std::hash::Hash,
    std::cmp::PartialEq,
    std::cmp::Eq,
    std::cmp::PartialOrd,
    std::cmp::Ord,
)]
#[repr(usize)]
pub enum MacroInvocationTailNonTerminals {
    MacroInvocationTail,
    NonEmptyMacroArgumentList,
    MacroArgumentListAfterLeadingComma,
    MacroArgumentLexeme,
    _Group8,
    __Group8Plus9,
    __Group8Star10,
    _MacroArgumentLexemePlus11,
    _MacroArgumentLexemeStar12,
    _LexicalTokenPlus14,
    _LexicalTokenStar15,
    _TermSet16,
    Augmented,
}
impl MacroInvocationTailNonTerminals {
    #[inline]
    pub fn from_usize(value: usize) -> Self {
        debug_assert!(
            value < 13usize,
            "Non-terminal index {} is out of bounds (max {})",
            value,
            13usize
        );
        unsafe { ::std::mem::transmute(value) }
    }
}
impl std::fmt::Display for MacroInvocationTailNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl std::fmt::Debug for MacroInvocationTailNonTerminals {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use ::rusty_lr::parser::nonterminal::NonTerminal;
        write!(f, "{}", self.as_str())
    }
}
impl ::rusty_lr::parser::nonterminal::NonTerminal for MacroInvocationTailNonTerminals {
    fn as_str(&self) -> &'static str {
        match self {
            MacroInvocationTailNonTerminals::MacroInvocationTail => "MacroInvocationTail",
            MacroInvocationTailNonTerminals::NonEmptyMacroArgumentList => {
                "NonEmptyMacroArgumentList"
            }
            MacroInvocationTailNonTerminals::MacroArgumentListAfterLeadingComma => {
                "MacroArgumentListAfterLeadingComma"
            }
            MacroInvocationTailNonTerminals::MacroArgumentLexeme => "MacroArgumentLexeme",
            MacroInvocationTailNonTerminals::_Group8 => "(comma, MacroArgument)",
            MacroInvocationTailNonTerminals::__Group8Plus9 => "(comma, MacroArgument)+",
            MacroInvocationTailNonTerminals::__Group8Star10 => "(comma, MacroArgument)*",
            MacroInvocationTailNonTerminals::_MacroArgumentLexemePlus11 => "MacroArgumentLexeme+",
            MacroInvocationTailNonTerminals::_MacroArgumentLexemeStar12 => "MacroArgumentLexeme*",
            MacroInvocationTailNonTerminals::_LexicalTokenPlus14 => "LexicalToken+",
            MacroInvocationTailNonTerminals::_LexicalTokenStar15 => "LexicalToken*",
            MacroInvocationTailNonTerminals::_TermSet16 => "[^]",
            MacroInvocationTailNonTerminals::Augmented => "Augmented",
        }
    }
    fn nonterm_type(&self) -> Option<::rusty_lr::parser::nonterminal::NonTerminalType> {
        match self {
            MacroInvocationTailNonTerminals::MacroInvocationTail => None,
            MacroInvocationTailNonTerminals::NonEmptyMacroArgumentList => None,
            MacroInvocationTailNonTerminals::MacroArgumentListAfterLeadingComma => None,
            MacroInvocationTailNonTerminals::MacroArgumentLexeme => None,
            MacroInvocationTailNonTerminals::_Group8 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Group)
            }
            MacroInvocationTailNonTerminals::__Group8Plus9 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusLeft)
            }
            MacroInvocationTailNonTerminals::__Group8Star10 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            MacroInvocationTailNonTerminals::_MacroArgumentLexemePlus11 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusLeft)
            }
            MacroInvocationTailNonTerminals::_MacroArgumentLexemeStar12 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            MacroInvocationTailNonTerminals::_LexicalTokenPlus14 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::PlusLeft)
            }
            MacroInvocationTailNonTerminals::_LexicalTokenStar15 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Star)
            }
            MacroInvocationTailNonTerminals::_TermSet16 => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::TerminalSet)
            }
            MacroInvocationTailNonTerminals::Augmented => {
                Some(::rusty_lr::parser::nonterminal::NonTerminalType::Augmented)
            }
        }
    }
    fn to_usize(&self) -> usize {
        *self as usize
    }
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub enum MacroInvocationTailData {
    __terminals(Token),
    __variant1((Vec<Vec<Token>>, Vec<Token>)),
    __variant2(Vec<Vec<Token>>),
    __variant3(Vec<Token>),
    Empty,
}
/// enum for each non-terminal and terminal symbol, that actually hold data
#[rustfmt::skip]
#[allow(unused_braces, unused_parens, non_snake_case, non_camel_case_types)]
pub struct MacroInvocationTailDataStack {
    pub __stack: Vec<MacroInvocationTailData>,
}
impl Default for MacroInvocationTailDataStack {
    fn default() -> Self {
        Self {
            __stack: Vec::new(),
        }
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut,
    dead_code
)]
impl MacroInvocationTailDataStack {
    fn custom_reduce_action_0(
        mut lexemes: Vec<Vec<Token>>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<Vec<Token>, ::rusty_lr::DefaultReduceActionError> {
        Ok({ lexemes.into_iter().flatten().collect() })
    }
    fn custom_reduce_action_1(
        mut lexemes: Vec<Vec<Token>>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<Vec<Token>, ::rusty_lr::DefaultReduceActionError> {
        Ok({ lexemes.into_iter().flatten().collect() })
    }
    ///MacroInvocationTail -> lparen rparen LexicalToken*
    #[inline]
    fn reduce_MacroInvocationTail_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        let mut tail = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        let __res = { (Vec::new(), tail) };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant1(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroInvocationTail -> lparen NonEmptyMacroArgumentList rparen LexicalToken*
    #[inline]
    fn reduce_MacroInvocationTail_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                3usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 4);
        let mut tail = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let mut arguments = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let __res = { (arguments, tail) };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant1(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///NonEmptyMacroArgumentList -> MacroArgumentLexeme+ (comma, MacroArgument)*
    #[inline]
    fn reduce_NonEmptyMacroArgumentList_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut rest = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let mut __rustylr_data_0 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __rustylr_data_0 = Self::custom_reduce_action_1(
            __rustylr_data_0,
            data,
            __rustylr_location0,
        )?;
        let mut argument = __rustylr_data_0;
        let __res = {
            let mut arguments = vec![argument];
            arguments.extend(rest);
            arguments
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///NonEmptyMacroArgumentList -> comma MacroArgumentListAfterLeadingComma
    #[inline]
    fn reduce_NonEmptyMacroArgumentList_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut rest = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let __res = {
            let mut arguments = vec![Vec::new()];
            arguments.extend(rest);
            arguments
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentListAfterLeadingComma -> MacroArgumentLexeme* (comma, MacroArgument)*
    #[inline]
    fn reduce_MacroArgumentListAfterLeadingComma_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut rest = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let mut __rustylr_data_0 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __rustylr_data_0 = Self::custom_reduce_action_0(
            __rustylr_data_0,
            data,
            __rustylr_location0,
        )?;
        let mut argument = __rustylr_data_0;
        let __res = {
            let mut arguments = vec![argument];
            arguments.extend(rest);
            arguments
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme -> lparen rparen
    #[inline]
    fn reduce_MacroArgumentLexeme_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        __data_stack.__stack.truncate(__data_stack.__stack.len() - 2);
        let __res = { vec![Token::LeftParen, Token::RightParen] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme -> lparen NonEmptyMacroArgumentList rparen
    #[inline]
    fn reduce_MacroArgumentLexeme_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                2usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 3);
        __data_stack.__stack.pop();
        let mut arguments = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let __res = { materialize_parenthesized_argument_list(arguments) };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme -> [other, ident, ..., <Others>]
    #[inline]
    fn reduce_MacroArgumentLexeme_2(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.pop();
        let mut token = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let __res = { vec![token] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///(comma, MacroArgument) -> comma MacroArgumentLexeme*
    #[inline]
    fn reduce__Group8_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut __rustylr_data_1 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        __data_stack.__stack.pop();
        let __rustylr_data_1 = Self::custom_reduce_action_0(
            __rustylr_data_1,
            data,
            __rustylr_location0,
        )?;
        let mut __token1 = __rustylr_data_1;
        let __res = __token1;
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///(comma, MacroArgument)+ -> (comma, MacroArgument)
    #[inline]
    fn reduce___Group8Plus9_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
        }
        __location_stack.pop();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let __res = { vec![A] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///(comma, MacroArgument)+ -> (comma, MacroArgument)+ (comma, MacroArgument)
    #[inline]
    fn reduce___Group8Plus9_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let mut Ap = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            Ap.push(A);
            Ap
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///(comma, MacroArgument)* -> (comma, MacroArgument)+
    #[inline]
    fn reduce___Group8Star10_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.pop();
        let mut __token0 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __res = __token0;
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///(comma, MacroArgument)* ->
    #[inline]
    fn reduce___Group8Star10_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        let __res = { vec![] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme+ -> MacroArgumentLexeme
    #[inline]
    fn reduce__MacroArgumentLexemePlus11_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
        }
        __location_stack.pop();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let __res = { vec![A] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme+ -> MacroArgumentLexeme+ MacroArgumentLexeme
    #[inline]
    fn reduce__MacroArgumentLexemePlus11_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let mut Ap = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            Ap.push(A);
            Ap
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme* -> MacroArgumentLexeme+
    #[inline]
    fn reduce__MacroArgumentLexemeStar12_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant2(_)))
            );
        }
        __location_stack.pop();
        let mut __token0 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant2(val) => val,
            _ => unreachable!(),
        };
        let __res = __token0;
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///MacroArgumentLexeme* ->
    #[inline]
    fn reduce__MacroArgumentLexemeStar12_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        let __res = { vec![] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant2(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///LexicalToken+ -> [^]
    #[inline]
    fn reduce__LexicalTokenPlus14_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
        }
        __location_stack.pop();
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let __res = { vec![A] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///LexicalToken+ -> LexicalToken+ [^]
    #[inline]
    fn reduce__LexicalTokenPlus14_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__terminals(_)))
            );
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                1usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
        }
        __location_stack.truncate(__location_stack.len() - 2);
        let mut A = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__terminals(val) => val,
            _ => unreachable!(),
        };
        let mut Ap = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let __res = {
            Ap.push(A);
            Ap
        };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///LexicalToken* -> LexicalToken+
    #[inline]
    fn reduce__LexicalTokenStar15_0(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)]
        {
            debug_assert!(
                matches!(__data_stack.__stack.get(__data_stack.__stack.len() - 1 -
                0usize), Some(& MacroInvocationTailData::__variant3(_)))
            );
        }
        __location_stack.pop();
        let mut __token0 = match __data_stack.__stack.pop().unwrap() {
            MacroInvocationTailData::__variant3(val) => val,
            _ => unreachable!(),
        };
        let __res = __token0;
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
    ///LexicalToken* ->
    #[inline]
    fn reduce__LexicalTokenStar15_1(
        __data_stack: &mut Self,
        __location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        __push_data: bool,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Token>,
        data: &mut (),
        __rustylr_location0: &mut ::rusty_lr::DefaultLocation,
    ) -> Result<(), ::rusty_lr::DefaultReduceActionError> {
        #[cfg(debug_assertions)] {}
        let __res = { vec![] };
        if __push_data {
            __data_stack.__stack.push(MacroInvocationTailData::__variant3(__res));
        } else {
            __data_stack.__stack.push(MacroInvocationTailData::Empty);
        }
        Ok(())
    }
}
#[rustfmt::skip]
#[allow(
    unused_braces,
    unused_parens,
    non_snake_case,
    non_camel_case_types,
    unused_variables
)]
impl ::rusty_lr::parser::data_stack::DataStack for MacroInvocationTailDataStack {
    type Term = Token;
    type NonTerm = MacroInvocationTailNonTerminals;
    type ReduceActionError = ::rusty_lr::DefaultReduceActionError;
    type UserData = ();
    type StartType = (Vec<Vec<Token>>, Vec<Token>);
    type Location = ::rusty_lr::DefaultLocation;
    fn pop_start(&mut self) -> Option<Self::StartType> {
        self.__stack.pop();
        match self.__stack.pop() {
            Some(MacroInvocationTailData::__variant1(val)) => Some(val),
            _ => None,
        }
    }
    fn pop(&mut self) {
        self.__stack.pop();
    }
    fn push_terminal(&mut self, term: Self::Term) {
        self.__stack.push(MacroInvocationTailData::__terminals(term));
    }
    fn push_empty(&mut self) {
        self.__stack.push(MacroInvocationTailData::Empty);
    }
    fn clear(&mut self) {
        self.__stack.clear();
    }
    fn reserve(&mut self, additional: usize) {
        self.__stack.reserve(additional);
    }
    fn split_off(&mut self, at: usize) -> Self {
        Self {
            __stack: self.__stack.split_off(at),
        }
    }
    fn truncate(&mut self, at: usize) {
        self.__stack.truncate(at);
    }
    fn append(&mut self, other: &mut Self) {
        self.__stack.append(&mut other.__stack);
    }
    fn reduce_action(
        data_stack: &mut Self,
        location_stack: &mut Vec<::rusty_lr::DefaultLocation>,
        push_data: bool,
        rule_index: usize,
        shift: &mut bool,
        lookahead: &::rusty_lr::TerminalSymbol<Self::Term>,
        user_data: &mut Self::UserData,
        location0: &mut Self::Location,
    ) -> Result<(), Self::ReduceActionError> {
        match rule_index {
            0usize => {
                Self::reduce_MacroInvocationTail_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            1usize => {
                Self::reduce_MacroInvocationTail_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            2usize => {
                Self::reduce_NonEmptyMacroArgumentList_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            3usize => {
                Self::reduce_NonEmptyMacroArgumentList_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            4usize => {
                Self::reduce_MacroArgumentListAfterLeadingComma_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            5usize => {
                Self::reduce_MacroArgumentLexeme_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            6usize => {
                Self::reduce_MacroArgumentLexeme_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            7usize => {
                Self::reduce_MacroArgumentLexeme_2(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            8usize => {
                Self::reduce__Group8_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            9usize => {
                Self::reduce___Group8Plus9_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            10usize => {
                Self::reduce___Group8Plus9_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            11usize => {
                Self::reduce___Group8Star10_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            12usize => {
                Self::reduce___Group8Star10_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            13usize => {
                Self::reduce__MacroArgumentLexemePlus11_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            14usize => {
                Self::reduce__MacroArgumentLexemePlus11_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            15usize => {
                Self::reduce__MacroArgumentLexemeStar12_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            16usize => {
                Self::reduce__MacroArgumentLexemeStar12_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            17usize => {
                Self::reduce__LexicalTokenPlus14_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            18usize => {
                Self::reduce__LexicalTokenPlus14_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            19usize => {
                Self::reduce__LexicalTokenStar15_0(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            20usize => {
                Self::reduce__LexicalTokenStar15_1(
                    data_stack,
                    location_stack,
                    push_data,
                    shift,
                    lookahead,
                    user_data,
                    location0,
                )
            }
            _ => {
                unreachable!("Invalid Rule: {}", rule_index);
            }
        }
    }
}
/// A lightweight parser struct that references the static parser tables and production rules.
///
/// Since this struct only holds `'static` references to shared, read-only static parser tables,
/// it is extremely cheap to instantiate, copy, or clone, and takes very little space.
#[allow(
    unused_braces,
    unused_parens,
    unused_variables,
    non_snake_case,
    unused_mut
)]
#[derive(Clone, Copy)]
pub struct MacroInvocationTailParser;
unsafe impl ::std::marker::Send for MacroInvocationTailParser {}
unsafe impl ::std::marker::Sync for MacroInvocationTailParser {}
#[rustfmt::skip]
impl ::rusty_lr::parser::Parser for MacroInvocationTailParser {
    type Term = Token;
    type TermClass = MacroInvocationTailTerminalClasses;
    type NonTerm = MacroInvocationTailNonTerminals;
    type StateIndex = u8;
    type ReduceRules = u8;
    type Tables = MacroInvocationTailTables;
    const ERROR_USED: bool = false;
    fn get_tables() -> &'static MacroInvocationTailTables {
        static TABLES: std::sync::OnceLock<MacroInvocationTailTables> = std::sync::OnceLock::new();
        TABLES
            .get_or_init(|| {
                static RULE_NAMES: &[u32] = &[
                    0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11,
                    11, 11, 11, 12,
                ];
                static RULE_LENGTHS: &[u32] = &[
                    3, 4, 2, 2, 2, 2, 3, 1, 2, 1, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 1,
                    1, 1, 2,
                ];
                static SHIFT_TERM_DATA: &[u32] = &[
                    2147516418, 2147549184, 2147581953, 2147614722, 2148171779,
                    2147549184, 2147614722, 2147549184, 2147581953, 2147614722,
                    2147647491, 2147713027, 2147549184, 2147811329, 2147614722,
                    2147549184, 2147614722, 2147549184, 2147614722, 2147811329,
                    2147811329, 2148302848, 2148302849, 2148302850, 2148302851,
                    2148237312, 2148237313, 2148237314, 2148237315, 2148368387,
                    2148302848, 2148302849, 2148302850, 2148302851, 2148466693,
                ];
                static SHIFT_TERM_OFFSETS: &[u32] = &[
                    0, 1, 5, 5, 7, 11, 11, 12, 12, 12, 15, 17, 19, 19, 19, 19, 20, 20,
                    20, 20, 21, 21, 25, 29, 29, 29, 29, 30, 34, 34, 35, 35,
                ];
                static SHIFT_NONTERM_DATA: &[u32] = &[
                    2148433920, 2148335617, 2147745795, 2147778567, 2148073474,
                    2147745795, 2147844103, 2148106248, 2147680257, 2147745795,
                    2147778567, 2147876867, 2147942404, 2147975173, 2148040710,
                    2147745795, 2147844103, 2147909640, 2147876867, 2148007940,
                    2147942404, 2147975173, 2148139014, 2148204553, 2148270090,
                    2148302859, 2148237323, 2148204553, 2148401162, 2148302859,
                ];
                static SHIFT_NONTERM_OFFSETS: &[u32] = &[
                    0, 1, 4, 4, 8, 11, 11, 11, 11, 11, 15, 18, 19, 19, 19, 19, 20, 20,
                    20, 20, 23, 23, 26, 27, 27, 27, 27, 27, 30, 30, 30, 30,
                ];
                static REDUCE_DATA: &[u32] = &[
                    0, 1, 7, 1, 1, 7, 2, 1, 7, 3, 1, 7, 1, 1, 16, 3, 1, 16, 0, 1, 5, 1,
                    1, 5, 2, 1, 5, 3, 1, 5, 0, 1, 6, 1, 1, 6, 2, 1, 6, 3, 1, 6, 0, 1, 13,
                    1, 1, 13, 2, 1, 13, 3, 1, 13, 3, 1, 12, 1, 1, 16, 3, 1, 16, 1, 1, 15,
                    3, 1, 15, 0, 1, 14, 1, 1, 14, 2, 1, 14, 3, 1, 14, 1, 1, 8, 3, 1, 8,
                    1, 1, 9, 3, 1, 9, 3, 1, 11, 1, 1, 10, 3, 1, 10, 3, 1, 2, 3, 1, 3, 3,
                    1, 12, 3, 1, 4, 5, 1, 20, 5, 1, 19, 0, 1, 18, 1, 1, 18, 2, 1, 18, 3,
                    1, 18, 5, 1, 18, 5, 1, 0, 0, 1, 17, 1, 1, 17, 2, 1, 17, 3, 1, 17, 5,
                    1, 17, 5, 1, 20, 5, 1, 1,
                ];
                static REDUCE_OFFSETS: &[u32] = &[
                    0, 0, 0, 12, 18, 18, 30, 30, 42, 54, 57, 63, 69, 81, 87, 93, 96, 102,
                    105, 108, 111, 114, 117, 120, 135, 138, 153, 153, 156, 159, 159, 159,
                ];
                static CAN_ACCEPT_ERROR: &[u8] = &[
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0,
                ];
                let num_rules = 26usize;
                let mut rules = Vec::with_capacity(num_rules);
                for i in 0..num_rules {
                    let lhs = MacroInvocationTailNonTerminals::from_usize(
                        RULE_NAMES[i] as usize,
                    );
                    rules
                        .push(::rusty_lr::parser::table::RuleInfo {
                            lhs,
                            len: RULE_LENGTHS[i] as usize,
                        });
                }
                let num_states = 31usize;
                let mut state_rows = Vec::with_capacity(num_states);
                for i in 0..num_states {
                    let term_start = SHIFT_TERM_OFFSETS[i] as usize;
                    let term_end = SHIFT_TERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_term = Vec::with_capacity(
                        term_end - term_start,
                    );
                    for idx in term_start..term_end {
                        let val = SHIFT_TERM_DATA[idx];
                        let term_class = MacroInvocationTailTerminalClasses::from_usize(
                            (val & 0x7fff) as usize,
                        );
                        let state = ((val >> 15) & 0xffff) as usize;
                        let push = (val >> 31) != 0;
                        shift_goto_map_term
                            .push((
                                term_class,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let nonterm_start = SHIFT_NONTERM_OFFSETS[i] as usize;
                    let nonterm_end = SHIFT_NONTERM_OFFSETS[i + 1] as usize;
                    let mut shift_goto_map_nonterm = Vec::with_capacity(
                        nonterm_end - nonterm_start,
                    );
                    for idx in nonterm_start..nonterm_end {
                        let val = SHIFT_NONTERM_DATA[idx];
                        let nonterm = MacroInvocationTailNonTerminals::from_usize(
                            (val & 0x7fff) as usize,
                        );
                        let state = ((val >> 15) & 0xffff) as usize;
                        let push = (val >> 31) != 0;
                        shift_goto_map_nonterm
                            .push((
                                nonterm,
                                ::rusty_lr::parser::table::ShiftTarget::new(state, push),
                            ));
                    }
                    let reduce_start = REDUCE_OFFSETS[i] as usize;
                    let reduce_end = REDUCE_OFFSETS[i + 1] as usize;
                    let mut reduce_map = Vec::new();
                    let mut idx = reduce_start;
                    while idx < reduce_end {
                        let term_val = REDUCE_DATA[idx];
                        let term_class = MacroInvocationTailTerminalClasses::from_usize(
                            term_val as usize,
                        );
                        let len = REDUCE_DATA[idx + 1] as usize;
                        let mut rules = Vec::with_capacity(len);
                        for r_idx in 0..len {
                            rules.push(REDUCE_DATA[idx + 2 + r_idx] as usize);
                        }
                        reduce_map.push((term_class, rules));
                        idx += 2 + len;
                    }
                    let can_accept_error = match CAN_ACCEPT_ERROR[i] {
                        0 => ::rusty_lr::TriState::False,
                        1 => ::rusty_lr::TriState::True,
                        2 => ::rusty_lr::TriState::Maybe,
                        _ => unreachable!(),
                    };
                    let intermediate = ::rusty_lr::parser::state::IntermediateState {
                        shift_goto_map_term,
                        shift_goto_map_nonterm,
                        reduce_map,
                        ruleset: Vec::new(),
                        can_accept_error,
                    };
                    state_rows.push(intermediate);
                }
                ::rusty_lr::parser::table::IntermediateTables {
                    state_rows,
                    rules,
                }
                    .into()
            })
    }
}

// ==============================Generated Codes End===============================
